#!/usr/bin/env python
import sys, os, urllib2, json, re, hashlib, time
from subprocess import check_output

hash_gen = hashlib.sha1()
gen_ts = str(time.time())

# Collect the parameters
commit_msg_filepath = sys.argv[1]
if len(sys.argv) > 2:
  commit_type = sys.argv[2]
else:
  commit_type = ''
if len(sys.argv) > 3:
   commit_hash = sys.argv[3]
else:
   hash_gen.update(gen_ts)
   commit_hash = hash_gen.hexdigest()
  
found_json_tracks = urllib2.urlopen("https://api.spotify.com/v1/search?q=" + "+".join(commit_hash[0:7]) + "&type=track").read()
parsed_json = json.loads(found_json_tracks)

print found_json_tracks

song_name = parsed_json['tracks']['items'][0]['name']
song_link = parsed_json['tracks']['items'][0]['external_urls']['spotify']
all_artists_from_first_song = parsed_json['tracks']['items'][0]['album']['artists']
all_artists_name = map(lambda x: x['name'], all_artists_from_first_song)
artist_names = reduce(lambda x, y: x + " " + y, all_artists_name)
with open(commit_msg_filepath, 'r+') as f:
	content = f.read()
	f.seek(0, 0)
	f.write("Listen to that song! : %s from %s \n\t Go get it %s" % (song_name, artist_names,song_link))

