#!/usr/bin/env python
import sys, os, urllib2, json, re 
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]
if len(sys.argv) > 2:
  commit_type = sys.argv[2]
else:
  commit_type = ''
if len(sys.argv) > 3:
   commit_hash = sys.argv[3]
else:
   commit_hash = 'abba'
  
foundJsonTracks = urllib2.urlopen("https://api.spotify.com/v1/search?q=" + "+".join(commit_hash[0:7]) + "&type=track").read()
parsedJSON = json.loads(foundJsonTracks)
with open(commit_msg_filepath, 'r+') as f:
	content = f.read()
	f.seek(0, 0)
	f.write("Listen to that song! : %s" % (parsedJSON['tracks']['items'][0]['name']))

